language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
env:
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=2.1
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
  - pip install -r requirements/dev.txt
# command to run tests
script:
  - ./tests/manage.py test